# Generated by Django 2.2 on 2019-11-16 17:15

import bot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Дисциплина')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Описание')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('file', models.FileField(upload_to=bot.models.upload_material_file_folder, verbose_name='Материал')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Themes')),
            ],
        ),
    ]
