# Generated by Django 2.2 on 2019-11-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20191116_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
